language: minimal
dist: focal

install:
  # Install Hugo (must be the "extended" version).
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
  # Install muffet (link checker).
  - curl -LO https://github.com/raviqqe/muffet/releases/download/v2.2.1/muffet_2.2.1_Linux_x86_64.tar.gz
  - tar zxf muffet_2.2.1_Linux_x86_64.tar.gz

script:
  # Build website.
  - hugo --debug --cleanDestinationDir --destination public-new --templateMetrics --templateMetricsHints
  # Compare new (public-new) website with previous version (public).
  - diff -aur public public-new
  # Start Hugo web server in the background to serve the website for link checking.
  # For some reason we need this --baseURL argument in place, otherwise muffet will give a lot of
  #   "dial tcp4 127.0.1.1:1313: connect: connection refused" and not be able to scrape the website.
  - hugo server --debug --baseURL http://127.0.0.1:1313/ --disableBrowserError --disableLiveReload &
  # Give Hugo ample time to start up before scraping.
  - sleep 15
  # Check for dead links and similar problems.
  - ./muffet http://127.0.0.1:1313
