language: minimal
dist: focal

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_0.74.3_Linux-64bit.deb
  - sudo apt install -y linkchecker

script:
  - hugo --debug --cleanDestinationDir --destination public-new --templateMetrics --templateMetricsHints
  - diff -aur public public-new
  - hugo server --debug --disableBrowserError --disableLiveReload --noHTTPCache
  - linkchecker --check-extern --no-robots http://127.0.0.1:1313
